server:
  port: 8003
spring:
  application:
    name: spring-boot-grpc-client

grpc:
  client:
    spring-boot-grpc-server:
      address: static://127.0.0.1:9898
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext